import '../styles/globals.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <div id="navigation" className="flex gap-4 py-3 px-8 bg-gray-600 text-gray-200">
                    <a className="decoration-none px-2 py-2 font-3xl hover:underline hover:transition-all hover:text-white hover:scale-125 hover:underline-offset-4" href="/">Home</a>
                    <a className="decoration-none px-2 py-2 font-3xl hover:underline hover:transition-all hover:text-white hover:scale-125 hover:underline-offset-4" href="/products">Products</a>
                    <a className="decoration-none px-2 py-2 font-3xl hover:underline hover:transition-all hover:text-white hover:scale-125 hover:underline-offset-4" href="/team">Team</a>
                    <a className="decoration-none px-4 py-2 font-3xl rounded-md bg-sky-400 hover:underline hover:transition-all text-black hover:scale-125 hover:underline-offset-4" href="/contact">Contact</a>
                </div>
                <div id="content" className="py-4 px-8">
                    {children}
                </div>
            </body>
        </html>
    )
}
